name: Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      IMAGE_TAG: latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build docker image
      - name: Build Docker image
        id: build-image
        run:  docker build -t $IMAGE_NAME .

      # Tag docker image
      - name: Tag Image
        id: tag-image
        run: docker tag $IMAGE_NAME $DOCKERHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
        
      - name: Push the image to Docker Hub
        id: push-image
        run: |
          echo "Pushing image to Docker Hub..."
          docker push $DOCKERHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
          echo "::set-output name=image::$DOCKERHUB_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG"

