name: CI - Scheduled

on:
  schedule:
    - cron: '0 7 * * 0' # Runs every Sunday at 7:00 AM UTC (which is 9:00 AM TLV)

jobs:
  run_tests:
    strategy:
      matrix:
        branch: [adapter-v2]
    uses: ./.github/workflows/test-workflow.yml
    with:
      branch: ${{ matrix.branch }}
    secrets: inherit

